### ISSUE TITLE
USER STORY: <ADD A POLL>

### ISSUE THREAD

**Issue by CHAMPION316** [CHAMPION316/My-first-Agile-Project-#3]
In order to **create an agreement with times and places for runnning** as a **administrator** I can **create a poll** that will allow our community to vote on such places and times. 

# Acceptance Criteria
- Talk to the community to discuss popular locations in the city and times
- Add the most popular locations within the city to run to the poll
- Have the running community vote on such poll

## Tasks:
- [ ] Create a poll with 4 options that highlight when mouse cursor rolls over them
- [ ] Upon choosing the poll options will highlight with two different colors for chosen and not
- [ ] Generate the percent of the total next to each poll option indicating which option is winning
